todo_main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.TodosPageView.as_view(), name='todos_page'),
    path('todos/', include('todos.urls', namespace='todos')),
]

todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'
urlpatterns = [
    path('add_todo/', views.AddTodoView.as_view(), name='add_todo'),
    path('done_todo/<int:todo_id>/', views.DoneTodoView.as_view(), name='done_todo'),
    path('undone_todo/<int:todo_id>/', views.UnDoneTodoView.as_view(), name='undone_todo'),
    path('edit_todo/<int:todo_id>/', views.EditTodoView.as_view(), name='edit_todo'),
    path('delete_todo/<int:todo_id>/', views.DeleteTodoView.as_view(), name='delete_todo'),
]

todos/models.py
from django.db import models

class Task(models.Model):
    task = models.CharField(max_length=250)
    is_completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.task

todo_main/views.py
from django.shortcuts import render, redirect
from django import views
from todos.models import Task


class TodosPageView(views.View):
    template_name = 'todos_page.html'
    def get(self, request):
        tasks = Task.objects.filter(is_completed=False).order_by('-updated_at')
        completed_tasks = Task.objects.filter(is_completed=True)
        return render(request, self.template_name, {'tasks':tasks, 'completed_tasks':completed_tasks})

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django import views
from .models import Task


class AddTodoView(views.View):
    def post(self, request):
        task = request.POST['task']
        Task.objects.create(task=task)
        return redirect('todos_page')

class DoneTodoView(views.View):
    def get(self, request, todo_id):
        task = get_object_or_404(Task, id=todo_id)
        task.is_completed = True
        task.save()
        return redirect('todos_page')

class UnDoneTodoView(views.View):
    def get(self, request, todo_id):
        task = get_object_or_404(Task, id=todo_id)
        task.is_completed = False
        task.save()
        return redirect('todos_page')

class EditTodoView(views.View):
    def get(self, request, todo_id):
        get_task = get_object_or_404(Task, id=todo_id)
        return render(request, 'todos/edit_todo.html', {'get_task':get_task})

    def post(self, request, todo_id):
        get_task = get_object_or_404(Task, id=todo_id)
        new_task = request.POST['task']
        get_task.task = new_task
        get_task.save()
        return redirect('todos_page')

class DeleteTodoView(views.View):
    def get(self, request, todo_id):
        get_task = get_object_or_404(Task, id=todo_id)
        get_task.delete()
        return redirect('todos_page')

home/templates/home/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST - Home</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .form-control{
        padding: 1.375rem .75rem !important;
    }
    </style>
</head>
<body>
    <div class="container">
        <h3 class="pt-5 text-center">Django ToDo App</h3>
        <div class="row">
            <h4>My Day</h4>
            <p class="text-muted">{% now "jS F Y" %}</p>
            <div class="col-md-7 col-lg-7" style="height: 450px; overflow: scroll;">
                <!-- List of all the tasks for the day -->
                <div class="card m-1">
                    <div class="card-body">
                        This is some Task
                        <span style="position: relative; float: right;">
                            <a class="btn btn-success"><i class="fa fa-check"></i> Mark as Done</a>
                            <a class="btn btn-danger"><i class="fa fa-trash"></i></a>
                            <a class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                        </span>
                    </div>
                </div>

            </div>
            <div class="col-md-5 col-lg-5">
                <h5>Completed Tasks</h5>
                <!-- List of all the tasks that have completed -->
                <div class="card m-1">
                    <div class="card-body">
                        This is the completed task.
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-6 p-0" style="position: absolute; bottom: 50px;">
                <!-- To Do Form -->
                <form action="" >
                    <div class="form-group">
                        <span style="display: flex;">
                            <input type="text" class="form-control" placeholder="Add a task">
                            <button class="btn btn-primary" style="width: 200px;"><i class="fa fa-plus"></i> Add</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/todos_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST - Home</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <style>
        .form-control{
        padding: 1.375rem .75rem !important;
    }
    </style>
</head>
<body>
    <div class="container">
        <h3 class="pt-5 text-center">Django ToDo App</h3>
        <div class="row">
            <h4>My Day</h4>
            <p class="text-muted">{% now "jS F Y" %}</p>
            <div class="col-md-7 col-lg-7" style="height: 450px; overflow: scroll;">
                <!-- List of all the tasks for the day -->
                {% for task in tasks %}
                    <div class="card m-1">
                        <div class="card-body">
                            {{ task.task }}
                            <span style="position: relative; float: right;">
                                <a class="btn btn-success" href="{% url 'todos:done_todo' task.id %}"><i class="fa fa-check"></i> Mark as Done</a>
                                <a class="btn btn-danger" href="{% url 'todos:delete_todo' task.id %}"><i class="fa fa-trash"></i></a>
                                <a class="btn btn-primary" href="{% url 'todos:edit_todo' task.id %}"><i class="fa fa-pencil"></i></a>
                            </span>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-md-5 col-lg-5">
                <h5>Completed Tasks</h5>
                <!-- List of all the tasks that have completed -->
                {% for completed_task in completed_tasks %}
                    <div class="card m-1">
                        <div class="card-body">
                            {{ completed_task }}
                            <a class="btn btn-success" href="{% url 'todos:undone_todo' completed_task.id %}"><i class="fa fa-check"></i> Mark as Undone</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-lg-6 p-0" style="position: absolute; bottom: 50px;">
                <!-- To Do Form -->
                <form action="{% url 'todos:add_todo' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <span style="display: flex;">
                            <input type="text" name="task" class="form-control" placeholder="Add a task">
                            <button type="submit" class="btn btn-primary" style="width: 200px;"><i class="fa fa-plus"></i> Add</button>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

todos/templates/todos/edit_todo.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Task - Django ToDo App</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
    <div class="container">
            <h3 class="pt-5 pb-5 text-center">Django ToDo App - Edit Task</h3>
            <form action="{% url 'todos:edit_todo' get_task.id%}" method="post" style="width: 500px; margin: auto">
                {% csrf_token %}
                <div class="form-group">
                    <span style="display: flex;">
                        <input type="text" name="task" class="form-control" placeholder="Add a task" value="{{ get_task.task }}">
                        <button type="submit" class="btn btn-primary" style="width: 200px;"><i class="fa fa-plus"></i>Update</button>
                    </span>
                </div>
            </form>
    </div>
</body>
</html>